### ISSUE TITLE
locale config step bevore running scripts

### ISSUE THREAD

**Issue by bornf** [r-darwish/alma#58]
setting up a different locale in a script gets overwritten by the hardcoded locale

**Comment by jamesmcm** [comment]
This is just because of the current order of operations:

The locale is set after running scripts: 

Running scripts L342: https://github.com/r-darwish/alma/blob/dcdce6f079113841d6ad7ec9d99395679a6274b4/src/main.rs#L342

Setting locale L409: https://github.com/r-darwish/alma/blob/dcdce6f079113841d6ad7ec9d99395679a6274b4/src/main.rs#L409

I think we can just move the setting the locale before the scripts, this shouldn't break anything. I'll do a quick test now and make a PR.

**Comment by bornf** [comment]
great, thanks...
